### ISSUE TITLE
please make your dependencies as devDependencies in package.json

### ISSUE THREAD

**Issue by xmlking** [manekinekko/angular-web-bluetooth#10]
please make your dependencies as devDependencies in package.json
lib users may be using newer versions of angular/core-js and it is unnecessary to  force them to download them when then run `yarn add @manekinekko/angular-web-bluetooth` 
```
    "dependencies": {
        "@angular/common": "^2.4.1",
        "@angular/core": "^2.4.1",
        "@angular/compiler": "^2.4.1",
        "@angular/platform-browser": "^2.4.1",
        "core-js": "2.4.1",
        "rxjs": "5.0.2",
        "zone.js": "0.7.4",
        "typescript": "2.0.10"
    },
```

**Comment by manekinekko** [comment]
@xmlking the dependencies used by this library must remain as `dependencies` because they are compiled with this library. 
However you are right, I shouldn't freeze deps version. I'll authorize patched version.
