### ISSUE TITLE
Angular 4.x OpaqueToken ->  InjectionToken

### ISSUE THREAD

**Issue by xmlking** [manekinekko/angular-web-bluetooth#15]
Hi @manekinekko just heads-up, Angular 4.x using `InjectionToken` in place of `OpaqueToken`
 
https://blog.thoughtram.io/angular/2016/05/23/opaque-tokens-in-angular-2.html#injectiontoken-since-angular-4x

**Comment by manekinekko** [comment]
Thanks @xmlking I'm already planning for the update when A4 is out.

**Comment by manekinekko** [comment]
fixed.
