### ISSUE TITLE
Unexpected value '[object Object]' imported by the module 'AppModule' error

### ISSUE THREAD

**Issue by damnko** [manekinekko/angular-web-bluetooth#17]
Hi, I am getting this error
```
Uncaught Error: Unexpected value '[object Object]' imported by the module 'AppModule'
    Zone.runTask @ zone.js:170
    ZoneTask.invoke @ zone.js:420
```
after I add
```
WebBluetoothModule.forRoot({
  enableTracing: true
}),
```
to the `imports` section of `AppModule`.

Do you have any suggestion on how to avoid that?
Thanks a lot

**Comment by manekinekko** [comment]
moved the discussion to the other repo https://github.com/JayKan/angular2-soundcloud/issues/2#issuecomment-291600986
