### ISSUE TITLE
This lib will read/listen 20 data sets per second which sent from BLE device?

### ISSUE THREAD

**Issue by narada85** [manekinekko/angular-web-bluetooth#21]

**Comment by manekinekko** [comment]
haven't tried that scenario before. Please do and tell us.

**Comment by narada85** [comment]
@manekinekko, I did the test, it subscribes to 2or 3 data sets per second. can we increase this by changing any settings in the lib?

**Comment by manekinekko** [comment]
I don't think we have control over this setting. Did you spot any documentation about this in the spec? Is there any public API?

**Comment by manekinekko** [comment]
I'm closing this issue. Please reopen if needed.
