### ISSUE TITLE
Documentation missing

### ISSUE THREAD

**Issue by Firefox2005** [manekinekko/angular-web-bluetooth#24]
Link seems to be broken. Would be very helpful to have the documentation.

**Comment by manekinekko** [comment]
Hi @Firefox2005 what kind of documentation you're looking for? Isn't the readme enough?

**Comment by Firefox2005** [comment]
Hey, in the readme you do mention the API in the section documentation. But the link to the API is broken - at least for me. Sorry for my misleading description.

**Comment by manekinekko** [comment]
sorry about this. the api documentation is hosted here: https://manekinekko.github.io/angular-web-bluetooth/
