### ISSUE TITLE
AOT compile Error

### ISSUE THREAD

**Issue by nilesh93** [manekinekko/angular-web-bluetooth#27]
Hi, I just followed the given example in the readme to include it to my angular 5 application and while the normal build works ok, the AOT build gives the following error.

ERROR in ../@manekinekko/angular-web-bluetooth/dist/lib/bluetooth.module.ts(29,2): Error during template compile of 'WebBluetoothModule'
  Function expressions are not supported in decorators in 'NgModule'
    'NgModule' contains the error at ../@angular/core/core.ts(194,31)
      Consider changing the function expression into an exported function.

**Comment by manekinekko** [comment]
see #29
