### ISSUE TITLE
Fail to build... ng build --prod

### ISSUE THREAD

**Issue by SauceCode84** [manekinekko/angular-web-bluetooth#29]
I am trying to build my Angular project using the CLI with the production flag, but I'm getting the following error.

ERROR in ..\\@manekinekko\angular-web-bluetooth\dist\lib\platform\browser.ts(3,2): Error during template compile of 'BrowserWebBluetooth'
  Function calls are not supported in decorators but 'ɵmakeDecorator' was called in 'Injectable'
    'Injectable' calls 'ɵmakeDecorator'.

Some info...
Angular Core: 5.2.0
Angular CLI: 1.6.8
Node: 8.9.1
OS: Windows 10 x64

Any assistance would be greatly appreciated.

**Comment by manekinekko** [comment]
Hi, the library is building fine with angular v5.2.4 (see [CI builds](https://circleci.com/gh/manekinekko/angular-web-bluetooth/65)).

Could you share a repro project so I can check?

**Comment by SauceCode84** [comment]
Updating to v2.1.0 solved the problem and the build is successful.

**Comment by antoinegilles** [comment]
hi ,
We have to updating the angular CLI version ?
