### ISSUE TITLE
error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'

### ISSUE THREAD

**Issue by krishan-gandhi2** [manekinekko/angular-web-bluetooth#33]
I have implemented the web-bluetooth module in same way but getting below error message , please help me to resolve this.
 

_ERROR in node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.
node_modules/@manekinekko/angular-web-bluetooth/node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'._

**Comment by manekinekko** [comment]
Hi, could you share some code so I can understand what's going on?

**Comment by ngfelixl** [comment]
Have the same issue importing your lib into existing project. Testing your _starter_ repo doesn't work either, but the error is another. Used `git clone yoururl`, `npm i`, `ng serve`.

`ng --version` output:
`
Angular CLI: 1.7.3
Node: 8.4.0
OS: win32 x64
Angular: 5.2.9
[...]
@angular/cli: 1.7.3
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.5.3
webpack: 3.11.0
`

The starter repo output error:

_ERROR in node_modules/@manekinekko/angular-web-bluetooth/node_modules/rxjs/observable/FromEventObservable.d.ts(23,22): error TS2415: Class 'FromEventObservable<T>' incorrectly extends base class 'Observable<T>'.
  Types of property '_subscribe' are incompatible.
    Type '(subscriber: Subscriber<T>) => void' is not assignable to type '(subscriber: Subscriber<any>) => TeardownLogic'.
      Types of parameters 'subscriber' and 'subscriber' are incompatible.
        Type 'Subscriber<any>' is not assignable to type 'Subscriber<T>'.
          Property 'isStopped' is protected but type 'Subscriber<T>' is not a class derived from
'Subscriber<T>'.
node_modules/@manekinekko/angular-web-bluetooth/node_modules/rxjs/observable/PromiseObservable.d.ts(10,22): error TS2415: Class 'PromiseObservable<T>' incorrectly extends base class 'Observable<T>'.  Types of property '_subscribe' are incompatible.
    Type '(subscriber: Subscriber<T>) => TeardownLogic' is not assignable to type '(subscriber: Subscriber<any>) => TeardownLogic'.      Types of parameters 'subscriber' and 'subscriber' are incompatible.        Type 'Subscriber<any>' is not assignable to type 'Subscriber<T>'.
          Property 'isStopped' is protected but type 'Subscriber<T>' is not a class derived from 'Subscriber<T>'._

**Comment by manekinekko** [comment]
Awesome! Would you mind sending a PR ?

**Comment by wojo1206** [comment]
@ngfelixl I installed your forked version I got 2 warnings but no errors :)
``` js
WARNING in ./node_modules/@manekinekko/angular-web-bluetooth/node_modules/@angular/core/fesm5/core.js
5569:15-36 Critical dependency: the request of a dependency is an expression

WARNING in ./node_modules/@manekinekko/angular-web-bluetooth/node_modules/@angular/core/fesm5/core.js
5581:15-102 Critical dependency: the request of a dependency is an expression
```
Project info:
```

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 6.0.1
Node: 9.3.0
OS: darwin x64
Angular: 6.0.1
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.1
@angular-devkit/build-angular     0.6.1
@angular-devkit/build-optimizer   0.6.1
@angular-devkit/core              0.6.1
@angular-devkit/schematics        0.6.1
@angular/flex-layout              5.0.0-beta.14-17a70ee
@angular/pwa                      0.6.1
@ngtools/webpack                  6.0.1
@schematics/angular               0.6.1
@schematics/update                0.6.1
rxjs                              6.1.0
typescript                        2.7.2
webpack                           4.6.0
```

**Comment by ngfelixl** [comment]
Didn‘t testet ng6.0.1 but I will have a look on monday. Does it work besides of this warnings? Do the warnings appear for ng 6.0.0 and rxjs 6.1.0?

**Comment by manekinekko** [comment]
v3.0.0 has been published to NPM. Could you please give it a try and let me know?

**Comment by manekinekko** [comment]
I'll close this issue. Please open a new one if needed.
