### ISSUE TITLE
app won't launch

### ISSUE THREAD

**Issue by lionben89** [manekinekko/angular-web-bluetooth#34]
after installing packages, and doing npm start, getting this error:
ERROR in node_modules/@manekinekko/angular-web-bluetooth/node_modules/rxjs/observable/FromEventObservable.d.ts(23,22): error TS2415: Class 'FromEventObservable<T>' incorrectly extends base class 'Observable<T>'.
  Types of property '_subscribe' are incompatible.
    Type '(subscriber: Subscriber<T>) => void' is not assignable to type '(subscriber: Subscriber<any>) => TeardownLogic'.
      Types of parameters 'subscriber' and 'subscriber' are incompatible.
        Type 'Subscriber<any>' is not assignable to type 'Subscriber<T>'.
          Property 'isStopped' is protected but type 'Subscriber<T>' is not a class derived from 'Subscriber<T>'.
node_modules/@manekinekko/angular-web-bluetooth/node_modules/rxjs/observable/PromiseObservable.d.ts(10,22): error TS2415: Class 'PromiseObservable<T>' incorrectly extends base class 'Observable<T>'.
  Types of property '_subscribe' are incompatible.
    Type '(subscriber: Subscriber<T>) => TeardownLogic' is not assignable to type '(subscriber: Subscriber<any>) => TeardownLogic'.
      Types of parameters 'subscriber' and 'subscriber' are incompatible.
        Type 'Subscriber<any>' is not assignable to type 'Subscriber<T>'.
          Property 'isStopped' is protected but type 'Subscriber<T>' is not a class derived from 'Subscriber<T>'.

**Comment by manekinekko** [comment]
I think this is due to the new RxJS api. I'll schedule an upgrade asap.

**Comment by manekinekko** [comment]
v3.0.0 has been published to NPM. Could you please give it a try and let me know. Thanks
