### ISSUE TITLE
Streaming of values stops working when the parameter enableTracing is set to false

### ISSUE THREAD

**Issue by manishbansal8843** [manekinekko/angular-web-bluetooth#41]
**Describe the bug**
Streaming of values stops working when the parameter enableTracing is set to false.

I created one application which reads pedeometer stats from smart band (BLE) and then display on the screen. Further, the values get refreshed when the someone wears the band and move. This functionality has been enabled by calling below function as described in ReadME.md

```
streamValues() {
    // call this method to get a stream of values emitted by the device
    return this.ble.streamValues$();//.pipe(map((value: DataView) => value.getUint8(0)));
  }
```

This works absolutely fine when enableTracing parameter is set to true inside the module configuration. However, it stops working when same is set to false.

**To Reproduce**
NA

**Expected behavior**
By setting enableTracing to false should not impact any functionality.

**Screenshots**
NA
**Desktop (please complete the following information):**
 NA

**Smartphone (please complete the following information):**
 - Device: Moto G4+
 - OS: Android 7
 - Browser Chrome
 - Version 67

**Additional context**
NA

**Comment by manekinekko** [comment]
It seems to work here...
![image](https://user-images.githubusercontent.com/1699357/49079223-53a5be80-f240-11e8-9032-d46612c307eb.png)

Can you try with the recent release v7.0.0 and reopen another issue? 

I'm closing this one.
