### ISSUE TITLE
Compile error report

### ISSUE THREAD

**Issue by n1705771** [manekinekko/angular-web-bluetooth#42]
I downloaded angular-web-bluetooth.
But when I run ng serve --open command, there is a error as below:

ERROR in ./src/app/app.module.ts
Module not found: Error: Can't resolve 'C:\Users\angular-web-bluetooth-master\dist\angular-web-bluetooth' in 'C:\Users\angular-web-bluetooth-master\src\app'
ERROR in ./src/app/battery-level/battery-level.service.ts
Module not found: Error: Can't resolve 'C:\Users\angular-web-bluetooth-master\dist\angular-web-bluetooth' in 'C:\Users\angular-web-bluetooth-master\src\app\battery-level'

Could you please check whey this error happens?

Thanks

**Comment by manekinekko** [comment]
Hi, could you run `npm run build` before `ng serve` and let me know?

**Comment by n1705771** [comment]
I have Installed npm and angular 6. My procedure is as below:
1.Download angular-web-bluetooth (zip file) into my PC.
2.Extract the folder angular-web-bluetooth-master

3.Run below command from Git bash.
$ cd angular-web-bluetooth-master
$ ng build angular-web-blutooth

Then I get the above errors.

**Comment by n1705771** [comment]
after reinstall bluetooth module, the issue is fixed. thanks
