### ISSUE TITLE
Error with Angular 4

### ISSUE THREAD

**Issue by mahmoudelgawad** [manekinekko/angular-web-bluetooth#49]
after installing the backage -> found version number error as the following:
![image](https://user-images.githubusercontent.com/27723764/46917438-929cef00-cfc7-11e8-91ab-f50af6b68b18.png)
I fix it manually edit version number in  "manekinekko-angular-web-bluetooth.metadata.json" file from "4" to "3"

after that there runtime error with angular 4 project
![image](https://user-images.githubusercontent.com/27723764/46917468-ec051e00-cfc7-11e8-9ad3-dab1cd91284e.png)

**Comment by manekinekko** [comment]
The current version of this library is meant for Angular v6. For older version of Angular, please use an older version of this lib.
