### ISSUE TITLE
Are multiple services per connection and characteristics per service supported?

### ISSUE THREAD

**Issue by ojousima** [manekinekko/angular-web-bluetooth#58]
Thanks for the awesome project :) 

I'm interested in supporting Nordic UART Service and battery level service at the same time. I'd need to share the connection between different characteristics and services at the same time. 

After a quick exploration of the project it seems that currently I'd need to disconnect from one characteristic before connecting to next, is this the case or did I miss something?

**Comment by ojousima** [comment]
I can now read several characteristics from single device, but reading value from each new characteristic requires me to go through device selection process again. Is there an easy way to programmatically try to read the characteristics on existing connection, without requiring user to reselect the device for each characteristic?

**Comment by manekinekko** [comment]
I am afraid that's a protection from the browser and I don't know if you can bypass it.

Closing this issue. Please open a new one if other errors show up.

**Comment by intensite** [comment]
> I am afraid that's a protection from the browser and I don't know if you can bypass it.

Do you have any links related to that?  This seems like a serious limitation. For complex devices it is strongly recommended to group characteristics in different services.  We can't ask the users to disconnect and reconnect to the same device every time?!
