### ISSUE TITLE
Does not support on mac Chrome build 76.

### ISSUE THREAD

**Issue by swj0418** [manekinekko/angular-web-bluetooth#60]
**Describe the bug**
Although this chrome (76) browser supports WebBluetoothAPI, it throws me an error

**To Reproduce**
1. from the mac connect to remote server.

**Expected behavior**
Works. I tried looking that the source code and compared it with other web bluetooth api services' source code, but it does not differ at all. Could not pinpoint where the problem is coming from.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Google Chrome
 - Version 76

**Additional context**
DashboardComponent.html:32 ERROR Error: Your browser does not support Smart Bluetooth. See http://caniuse.com/#search=Bluetooth for more details.
    at new BrowserWebBluetooth (manekinekko-angular-web-bluetooth.js:15)
    at browserWebBluetooth (manekinekko-angular-web-bluetooth.js:803)
    at _callFactory (core.js:19825)
    at _createProviderInstance (core.js:19783)
    at resolveNgModuleDep (core.js:19744)
    at NgModuleRef_.push../node_modules/@angular/core/fesm5/core.js.NgModuleRef_.get (core.js:20452)
    at resolveDep (core.js:20823)
    at callFactory (core.js:20716)
    at _createProviderInstance$1 (core.js:20682)
    at createProviderInstance (core.js:20557)
View_DashboardComponent_0 @ DashboardComponent.html:32
proxyClass @ compiler.js:17945
push../node_modules/@angular/core/fesm5/core.js.DebugContext_.logError @ core.js:22708
push../node_modules/@angular/core/fesm5/core.js.ErrorHandler.handleError @ core.js:14624
(anonymous) @ core.js:16706
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:388
push../node_modules/zone.js/dist/zone.js.Zone.run @ zone.js:138
push../node_modules/@angular/core/fesm5/core.js.NgZone.runOutsideAngular @ core.js:16094
(anonymous) @ core.js:16706
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:388
onInvoke @ core.js:16135
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:387
push../node_modules/zone.js/dist/zone.js.Zone.run @ zone.js:138
(anonymous) @ zone.js:872
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:421
onInvokeTask @ core.js:16126
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:420
push../node_modules/zone.js/dist/zone.js.Zone.runTask @ zone.js:188
drainMicroTaskQueue @ zone.js:595
Promise.then (async)
scheduleMicroTask @ zone.js:578
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ zone.js:410
push../node_modules/zone.js/dist/zone.js.Zone.scheduleTask @ zone.js:232
push../node_modules/zone.js/dist/zone.js.Zone.scheduleMicroTask @ zone.js:252
scheduleResolveOrReject @ zone.js:862
ZoneAwarePromise.then @ zone.js:962
push../node_modules/@angular/core/fesm5/core.js.PlatformRef.bootstrapModule @ core.js:16639
./src/main.ts @ main.ts:12
__webpack_require__ @ bootstrap:78
0 @ main.ts:13
__webpack_require__ @ bootstrap:78
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ main.js:1
DashboardComponent.html:32 ERROR CONTEXT DebugContext_ {view: {…}, nodeIndex: 43, nodeDef: {…}, elDef: {…}, elView: {…}}
View_DashboardComponent_0 @ DashboardComponent.html:32
proxyClass @ compiler.js:17945
push../node_modules/@angular/core/fesm5/core.js.DebugContext_.logError @ core.js:22708
push../node_modules/@angular/core/fesm5/core.js.ErrorHandler.handleError @ core.js:14629
(anonymous) @ core.js:16706
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:388
push../node_modules/zone.js/dist/zone.js.Zone.run @ zone.js:138
push../node_modules/@angular/core/fesm5/core.js.NgZone.runOutsideAngular @ core.js:16094
(anonymous) @ core.js:16706
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:388
onInvoke @ core.js:16135
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:387
push../node_modules/zone.js/dist/zone.js.Zone.run @ zone.js:138
(anonymous) @ zone.js:872
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:421
onInvokeTask @ core.js:16126
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:420
push../node_modules/zone.js/dist/zone.js.Zone.runTask @ zone.js:188
drainMicroTaskQueue @ zone.js:595
Promise.then (async)
scheduleMicroTask @ zone.js:578
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ zone.js:410
push../node_modules/zone.js/dist/zone.js.Zone.scheduleTask @ zone.js:232
push../node_modules/zone.js/dist/zone.js.Zone.scheduleMicroTask @ zone.js:252
scheduleResolveOrReject @ zone.js:862
ZoneAwarePromise.then @ zone.js:962
push../node_modules/@angular/core/fesm5/core.js.PlatformRef.bootstrapModule @ core.js:16639
./src/main.ts @ main.ts:12
__webpack_require__ @ bootstrap:78
0 @ main.ts:13
__webpack_require__ @ bootstrap:78
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ main.js:1
main.ts:13 Error: Your browser does not support Smart Bluetooth. See http://caniuse.com/#search=Bluetooth for more details.
    at new BrowserWebBluetooth (manekinekko-angular-web-bluetooth.js:15)
    at browserWebBluetooth (manekinekko-angular-web-bluetooth.js:803)
    at _callFactory (core.js:19825)
    at _createProviderInstance (core.js:19783)
    at resolveNgModuleDep (core.js:19744)
    at NgModuleRef_.push../node_modules/@angular/core/fesm5/core.js.NgModuleRef_.get (core.js:20452)
    at resolveDep (core.js:20823)
    at callFactory (core.js:20716)
    at _createProviderInstance$1 (core.js:20682)
    at createProviderInstance (core.js:20557)

**Comment by manekinekko** [comment]
Try enabling the feature in your chrome: `chrome://flags/#enable-experimental-web-platform-features`
