### ISSUE TITLE
How to use custom service

### ISSUE THREAD

**Issue by Puneetkumarpal** [manekinekko/angular-web-bluetooth#61]
hi,

i want to communicate by device with hm10 (BLE module). it use service 0xFFE0 and characteristics 0xFFE1 for send and receive data. how can i communicate to this device it's show me an error

> manekinekko-angular-web-bluetooth.js:95 TypeError: Failed to execute 'requestDevice' on 'Bluetooth': Invalid Service name: 'ffe0'. It must be a valid UUID alias (e.g. 0x1234), UUID (lowercase hex characters e.g. '00001234-0000-1000-8000-00805f9b34fb'), or recognized standard name from https://www.bluetooth.com/specifications/gatt/services e.g. 'alert_notification'.
>     at BrowserWebBluetooth.push../dist/manekinekko/angular-web-bluetooth/fesm5/manekinekko-angular-web-bluetooth.js.BrowserWebBluetooth.requestDevice (manekinekko-angular-web-bluetooth.js:27)

Please help me as soon as possible

**Comment by NidasioAlberto** [comment]
I've the same issue

**Comment by manekinekko** [comment]
Thanks @NidasioAlberto for providing a quick answer.
