### ISSUE TITLE
Question: BluetoothCore extends Subject<BluetoothCore>?

### ISSUE THREAD

**Issue by troywweber7** [manekinekko/angular-web-bluetooth#63]
This is a question rather than a bug I suspect, but why does your `BluetoothCore` service extend an rxjs `Subject`? I suspect there could be a good reason, but I can't quite figure it out from your application. Thanks.

**Comment by manekinekko** [comment]
You are right that's a left out code from a previous implementation where BluetoothCore was behaving as a Subject (aka. service bus pattern).
