### ISSUE TITLE
Request: Make the service reusable for multiple components

### ISSUE THREAD

**Issue by intensite** [manekinekko/angular-web-bluetooth#64]
**Is your feature request related to a problem? Please describe.**

I have a custom device that communicates over multiple BLE characteristics (approx. 10).

The communications are mainly one way (read only) from the device to the web webapp.  One exception is a "command" characteristic that is used to send a set of pre-defined commands to the device.  

The whole application will use multiple Angular components on a certain number of pages. 

As of now, I have to create an instance of the Angular-Web-Bluetooth Service for each component/characteristic.  This is not practical and surely not scalable. 

**Describe the solution you'd like**

What I would like, is the service to be centralized to the main app.component and be shared throughout all the components.  
A suggestion would be to implement a getCharacteristic**s** **(note the S)** in the bluetooth.service.ts 

The resulting collection of characteristics could be saved or cached for later reuse.  The library user could then subscribe to observables events of one or many characteristics for notifications.

Here is a sample of what it could look like from 
https://googlechrome.github.io/samples/web-bluetooth/discover-services-and-characteristics-async-await.html

```
try {
    log('Requesting any Bluetooth Device...');
    const device = await navigator.bluetooth.requestDevice({
     // filters: [...] <- Prefer filters to save energy & show relevant devices.
        acceptAllDevices: true,
        optionalServices: optionalServices});

    log('Connecting to GATT Server...');
    const server = await device.gatt.connect();

    // Note that we could also get all services that match a specific UUID by
    // passing it to getPrimaryServices().
    log('Getting Services...');
    const services = await server.getPrimaryServices();

    log('Getting Characteristics...');
    for (const service of services) {
      log('> Service: ' + service.uuid);
      const characteristics = await service.getCharacteristics();   //  <==== This =====

      characteristics.forEach(characteristic => {      
        log('>> Characteristic: ' + characteristic.uuid + ' ' +
            getSupportedProperties(characteristic));
      });
    }
```
I am still a newby related to Angular, Rx.js and observable. So it is outside of my league currently. But I am learning fast :-)

**Additional context**
You can see a sample of my application here on github pages:  https://intensite.github.io/morgan-app/

The source code of the web-app is here: https://github.com/intensite/morgan-app

Thanks for this great library by the way!

**Comment by intensite** [comment]
I was able to achieve what I wanted by rewriting most of the ble.service.ts to use BehaviorSubject.  
Removing dependency to the method this.ble.value$() was the key.

**Comment by manekinekko** [comment]
That's awesome @intensite !! Thanks for letting us know.
