### ISSUE TITLE
Support batch mode.

### ISSUE THREAD

**Issue by manekinekko** [manekinekko/angular-web-bluetooth#65]
**Describe the solution you'd like**
We need to support requesting multiple services and characteristics at once.

**Comment by manekinekko** [comment]
Here is a WIP: https://github.com/manekinekko/angular-web-bluetooth/commit/86bd5ef216d3f69447b398a7be53f984868655f8

**Comment by fayway** [comment]
Hi @manekinekko, I would like to participate.
Little #opensource 101 question: I did 2 or 3 microscopic pull requests before to other projects but it always came from me. How does issue assignment work in an open source projects to prevent multiple people from working on the same thing?

**Comment by manekinekko** [comment]
Hey @fayway good to see you here.

Usually, we assign to issue to the person who is working on it. But, that person doesn't have write access to the repo, we try to agree who is working on which issue. You do that by leaving a comment on the issue thread and telling the team you are working on the issue.

Which is what you did here :) 

Please feel free to explore the code base and let me know if you have questions about this particular issue.

Thank you 😉

**Comment by fayway** [comment]
Okey dokey, I will start asap and let you know if I have any question.
Thanks

**Comment by manekinekko** [comment]
Thank you so much!

**Comment by manekinekko** [comment]
Fixed by @fayway in #76
