### ISSUE TITLE
Demo is not working on iOS safari

### ISSUE THREAD

**Issue by roip890** [manekinekko/angular-web-bluetooth#67]
The demo is not working on iOS safari browser. Do you have any ideas?

**Comment by vpalaciopbcs** [comment]
As far as I know web Bluetooth is not supported by Safari https://caniuse.com/#search=bluetooth

**Comment by manekinekko** [comment]
Thank you @vpalaciopbcs. 
Sorry, @roip890 that's correct. WebBLE is not supported in iOS Safari.
