### ISSUE TITLE
Module is not Found

### ISSUE THREAD

**Issue by ramirez-sebas1010** [manekinekko/angular-web-bluetooth#75]
**Describe the bug**
After installing it using npm i -S @manekinekko/angular-web-bluetooth @types/web-bluetooth, when I try to import the web module it is not found. 

**To Reproduce**
1. Install the Web Bluetooth Module
2. Go to App.module.ts
3. Try to import WebBluetoothModule  from @manekinekko/angular-web-bluetooth

**Expected behavior**
No error when I import the Module, so I can use it.

**Screenshots**
![Screenshot (181)](https://user-images.githubusercontent.com/61977214/110810798-e5486700-8264-11eb-99ba-fea60f8a5b7a.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: chrome

*Comments*
Angular Version:
![Screenshot (182)](https://user-images.githubusercontent.com/61977214/110811788-c5657300-8265-11eb-8120-0783f0b6b6d8.png)

**Comment by manekinekko** [comment]
It looks like this is the same issue as https://github.com/manekinekko/angular-web-bluetooth/issues/72

**Comment by ramirez-sebas1010** [comment]
> It looks like this is the same issue as https://github.com/manekinekko/angular-web-bluetooth/issues/72

Ohh ok, thanks I guess I just didn't understand ver well the solution, I'll check it out. Thank you 😄

**Comment by manekinekko** [comment]
No worries ☺️

I am still trying to figure out a correct way to fix #72

**Comment by ramirez-sebas1010** [comment]
I don't know if it helps but, I just cloned your project and updated some dependencies for my version of Angular and Node.
1) npm outdated
2) npm update
3) npx npm-check-updates -u
4) npm install
5) Update Chokidar
5) npm install typescript@">=4.0.0 and <4.2.0" --save-dev

Also, what solved most of the errors would be adding reference types="web-bluetooth" to everywhere that is using the Bluetooth Types from the Web Bluetooth API, and it works when you import from the public apis.

![image](https://user-images.githubusercontent.com/61977214/110842417-d3c38700-8285-11eb-9cf1-196ec2da2f7d.png)

![image](https://user-images.githubusercontent.com/61977214/110842542-fe154480-8285-11eb-9ce4-88bc4a9e6dd1.png)

Hope you can fix it 😁

**Comment by manekinekko** [comment]
This issues has been fixed in. Please install new version `@manekinekko/angular-web-bluetooth@11.2.2`. Please feel free to close this issue once you've confirmed it's working for you.

**Comment by ramirez-sebas1010** [comment]
Awesome! It's working very well. 
Thankss! 😎😎
