### ISSUE TITLE
Does not support on windows Chrome build 90.

### ISSUE THREAD

**Issue by LePandaRoox** [manekinekko/angular-web-bluetooth#78]
**Describe the bug**
Although this chrome (90) browser supports WebBluetoothAPI, it throws me an error.

**To Reproduce**
1. from Windows connect to OVH remote server.

**Expected behavior**
Works. Enabling the feature in my chrome: 'chrome: // flags / # enable-experimental-web-platform-features' is not working either.

**Screenshots**
The error in the browser console (F12).
![image](https://user-images.githubusercontent.com/33151409/119231858-24c3e700-bb23-11eb-8dcc-cbdf294c1d16.png)

The feature enabled in chrome
![image](https://user-images.githubusercontent.com/33151409/119231978-aa479700-bb23-11eb-899d-6685e00e5247.png)

**Desktop (please complete the following information):**
 - OS: WindowsOS
 - Browser Google Chrome
 - Version 90.0.4430.212

**Additional context**
Uncaught Error: Your browser does not support Smart Bluetooth. See http://caniuse.com/#search=Bluetooth for more details.
    at new DE (main-es2015.982b833fd5f46f2dbe4a.js:1)
    at FE (main-es2015.982b833fd5f46f2dbe4a.js:1)
    at main-es2015.982b833fd5f46f2dbe4a.js:1
    at Kl (main-es2015.982b833fd5f46f2dbe4a.js:1)
    at Xl (main-es2015.982b833fd5f46f2dbe4a.js:1)
    at main-es2015.982b833fd5f46f2dbe4a.js:1
    at Kl (main-es2015.982b833fd5f46f2dbe4a.js:1)
    at Xl (main-es2015.982b833fd5f46f2dbe4a.js:1)
    at du.get (main-es2015.982b833fd5f46f2dbe4a.js:1)
    at Qn (main-es2015.982b833fd5f46f2dbe4a.js:1)

**Comment by manekinekko** [comment]
Hi, I am sorry I am not able to support you on this issue. This is outside of the scope of this library. Please contact OVH for support.
