### ISSUE TITLE
How to get Temperature from BLE

### ISSUE THREAD

**Issue by TwaKattan** [manekinekko/angular-web-bluetooth#79]
Dear Friend,

Hope you are good and doing great, just want to ask a question. I have Xiaomi BLE device which gives me Temperature on a device but after I try your example web port its connect my device but it does not show any Temperature. Is portal support the Temperature part? or you are working on that?

https://web-platform-awesome-demos.firebaseapp.com/#/api/web-bluetooth

**Comment by manekinekko** [comment]
Hey, thank you for opening this question. Each device is unique, the sample app I provide does only work with the device I had. Each manufacturer has a priority communication protocol. you have to read their specification and use the right UUID and decoder to read the values.
