### ISSUE TITLE
Angular app cannot open in unsupported browser

### ISSUE THREAD

**Issue by Vadalarm-IT-Admin** [manekinekko/angular-web-bluetooth#80]
I use the angulat-web-bluetooth package in my Angular project, however if I open it in Safari then I only see a white screen with the following console message: 
`Error: Uncaught (in promise): Error: Your browser does not support Smart Bluetooth. See http://caniuse.com/#search=Bluetooth for more details.`
I would like to to open the web app even if the browser is not supported and the web bluetooth can't be used. What can i do in such a case? @manekinekko

**Comment by manekinekko** [comment]
Hey @Vadalarm-IT-Admin you can first check if Web BLE is supported by the browser. Here is an example:

```javascript
function isWebBluetoothEnabled() {
  return navigator.bluetooth;
}
```

**Comment by Vadalarm-IT-Admin** [comment]
I have skipped the dependency injection in case of the BluetoothCore, I have created new BluetoothCore object in a function:
```
let ble: BluetoothCore = new BluetoothCore(
      new BrowserWebBluetooth(),
      console
);
```
