### ISSUE TITLE
Upgrade to Angular v12 - v13

### ISSUE THREAD

**Issue by myoungFocus** [manekinekko/angular-web-bluetooth#81]
Looking at the commit comments from the last version it appears that last upgrade included support for version 11 of angular. 

Feature Request to upgrade the module to be compatible with newer versions of angular.

**Comment by jasdillon** [comment]
Yup, same issue here!

**Comment by OmarKhanfer** [comment]
Same here

**Comment by manekinekko** [comment]
Hi, you can find all released for angular v15 and before at:
- https://github.com/manekinekko/angular-web-bluetooth/releases/tag/v13.0.0 ([npm](https://www.npmjs.com/package/@manekinekko/angular-web-bluetooth/v/13.0.0))
- https://github.com/manekinekko/angular-web-bluetooth/releases/tag/v14.0.0 ([npm](https://www.npmjs.com/package/@manekinekko/angular-web-bluetooth/v/14.0.0))
- https://github.com/manekinekko/angular-web-bluetooth/releases/tag/v15.0.0 ([npm](https://www.npmjs.com/package/@manekinekko/angular-web-bluetooth/v/15.0.0))
