### ISSUE TITLE
Support for Angular v15

### ISSUE THREAD

**Issue by 0xFACE** [manekinekko/angular-web-bluetooth#82]
Please upgrade packagg.

**Comment by manekinekko** [comment]
Hi, you can find all released for angular v15 and before at:
- https://github.com/manekinekko/angular-web-bluetooth/releases/tag/v13.0.0 ([npm](https://www.npmjs.com/package/@manekinekko/angular-web-bluetooth/v/13.0.0))
- https://github.com/manekinekko/angular-web-bluetooth/releases/tag/v14.0.0 ([npm]
