### ISSUE TITLE
Support for Angular v17

### ISSUE THREAD

**Issue by 0xFACE** [manekinekko/angular-web-bluetooth#90]
Please update package to Angular v17

**Comment by 0xFACE** [comment]
up

**Comment by SilviaCarrozzo** [comment]
I also need the support for Angular v.17, thanks.

**Comment by manekinekko** [comment]
[v17 has been released](https://github.com/manekinekko/angular-web-bluetooth/releases/tag/v17.0.0). Enjoy!

**Comment by 0xFACE** [comment]
The issue still exists:
```
npm install @manekinekko/angular-web-bluetooth@17
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: uds-web@0.0.0
npm ERR! Found: @angular/common@17.1.3
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"^17.1.3" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^15.0.0" from @manekinekko/angular-web-bluetooth@17.0.0
npm ERR! node_modules/@manekinekko/angular-web-bluetooth
npm ERR!   @manekinekko/angular-web-bluetooth@"17" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR!
npm ERR! For a full report see:
```
It looks like the project in the **projects/manekinekko/angular-web-bluetooth** directory also needs to be updated.

**Comment by manekinekko** [comment]
Interesting. I can't reproduce the issue locally. What's your npm version?

![image](https://github.com/manekinekko/angular-web-bluetooth/assets/1699357/55e84cf7-bf62-4ccd-9734-770de4b58f71)

**Comment by 0xFACE** [comment]
Hi. I'm using mpn version 10.1.0 .

**Comment by manekinekko** [comment]
Thank you. Will publish a new release asap.

**Comment by manekinekko** [comment]
[v17.1.0 has been published](https://github.com/manekinekko/angular-web-bluetooth/releases/tag/v17.1.0). Please let me know if you are having other issues.

**Comment by 0xFACE** [comment]
Perfect, no issues. Thanks!
